services:
  backend:
    container_name: fullstack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/keys:/app/keys
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env.docker
    # Note: This service uses Turso database (remote), not PostgreSQL
    depends_on:
      - redis
    networks:
      - fullstack-network
    restart: unless-stopped

  frontend:
    container_name: fullstack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/public:/app/public
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - fullstack-network
    restart: unless-stopped

  redis:
    container_name: fullstack-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fullstack-network
    restart: unless-stopped

# Note: PostgreSQL and PgAdmin services have been removed as the application uses Turso database

networks:
  fullstack-network:
    driver: bridge

volumes:
  redis_data: 