package docs

// This file is used for Swagger documentation
// It will be auto-generated by swag init command

// @title           Fullstack API
// @version         1.0
// @description     A modern fullstack application with Go and Next.js

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
